#端口
server:
  port: 18082

#服务名
spring:
  application:
    name: demo-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    #在url后增加时区 &serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 192.168.244.4
    username: myredis
    password: myredis

#注册中心IP地址
eureka:
  instance:
    hostname: localhost
  client:
    #不向注册中心注册自己
    register-with-eureka: true
    #不检测自己(注册中心)的服务信息
    fetch-registry: true
    #注册地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:18081/eureka/

#控制台打印sql语句
logging:
  level:
    com:
      model:
        xd:
          demo:
            mapper: debug
